export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAIL = 'GET_POSTS_FAIL';
export const ADD_POSTS_SUCCESS = 'ADD_POSTS_SUCCESS';
export const ADD_POSTS_FAIL = 'ADD_POSTS_FAIL';

export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const CHECK_LANGUAGE = 'CHECK_LANGUAGE';
